<a href="https://colab.research.google.com/github/fadilaananta/netflix_recommender/blob/main/Netflix_Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import General Libraries and Datasets**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
netflix = pd.read_csv('/content/drive/MyDrive/Dataset/Netflix/netflix_titles.csv')
imdb = pd.read_csv('/content/drive/MyDrive/Dataset/Netflix/MoviesOnStreamingPlatforms_updated.csv')
netflix.head()

show_id  ...                                        description
0  81145628  ...  Before planning an awesome wedding for his gra...
1  80117401  ...  Jandino Asporaat riffs on the challenges of ra...
2  70234439  ...  With the help of three human allies, the Autob...
3  80058654  ...  When a prison ship crash unleashes hundreds of...
4  80125979  ...  When nerdy high schooler Dani finally attracts...

[5 rows x 12 columns]

**Preprocessing the dataset**

In [ ]:
netflix.drop(['show_id', 'listed_in'], axis=1, inplace=True)

In [ ]:
imdb.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
imdb.drop(['Netflix', 'Hulu', 'Prime Video', 'Disney+', 'Type'], axis=1, inplace=True)

In [ ]:
netflix.rename(columns={'title':'Title', 'release_year':'Year', 'director':'Directors', 'country':'Country'}, inplace=True)

In [ ]:
netflix.head()

type  ...                                        description
0    Movie  ...  Before planning an awesome wedding for his gra...
1    Movie  ...  Jandino Asporaat riffs on the challenges of ra...
2  TV Show  ...  With the help of three human allies, the Autob...
3  TV Show  ...  When a prison ship crash unleashes hundreds of...
4    Movie  ...  When nerdy high schooler Dani finally attracts...

[5 rows x 10 columns]

In [ ]:
netflix.isna().sum()

type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
description        0
dtype: int64

In [ ]:
imdb.columns

Index(['Unnamed: 0', 'ID', 'Title', 'Year', 'Age', 'IMDb', 'Rotten Tomatoes',
       'Netflix', 'Hulu', 'Prime Video', 'Disney+', 'Type', 'Directors',
       'Genres', 'Country', 'Language', 'Runtime'],
      dtype='object')

In [ ]:
imdb.isna().sum()

Unnamed: 0             0
ID                     0
Title                  0
Year                   0
Age                 9390
IMDb                 571
Rotten Tomatoes    11586
Netflix                0
Hulu                   0
Prime Video            0
Disney+                0
Type                   0
Directors            726
Genres               275
Country              435
Language             599
Runtime              592
dtype: int64

In [ ]:
imdb.head()

Unnamed: 0  ID  ...                 Language  Runtime
0           0   1  ...  English,Japanese,French    148.0
1           1   2  ...                  English    136.0
2           2   3  ...                  English    149.0
3           3   4  ...                  English    116.0
4           4   5  ...                  Italian    161.0

[5 rows x 17 columns]

In [ ]:
imdb.set_index('ID', inplace=True)

In [ ]:
print(imdb.shape)
print(netflix.shape)

(16744, 10)
(6234, 10)


**Merge both datasets**

In [ ]:
gabung = pd.merge(netflix.drop_duplicates(), imdb, how='inner', on='Title')
gabung.drop(['Directors_x', 'Year_x', 'Country_y'], axis=1, inplace=True)
gabung.rename(columns={'Directors_y':'Directors', 'Country_x':'Country', 'Year_y':'Year'}, inplace=True)
gabung.head()

type                                    Title  ... Language Runtime
0  Movie  Norm of the North: King Sized Adventure  ...  English    90.0
1  Movie                             #realityhigh  ...  English    99.0
2  Movie                                 Automata  ...  English   109.0
3  Movie       Fabrizio Copano: Solo pienso en mi  ...  Spanish     NaN
4  Movie                              Good People  ...  English    90.0

[5 rows x 23 columns]

In [ ]:
gabung.Genres = gabung.Genres.str.replace('-', '')

In [ ]:
gabung.head()

type                                    Title  ... Language Runtime
0  Movie  Norm of the North: King Sized Adventure  ...  English    90.0
1  Movie                             #realityhigh  ...  English    99.0
2  Movie                                 Automata  ...  English   109.0
3  Movie       Fabrizio Copano: Solo pienso en mi  ...  Spanish     NaN
4  Movie                              Good People  ...  English    90.0

[5 rows x 23 columns]

In [ ]:
gabung.drop(['cast'], axis=1, inplace=True)

In [ ]:
gabung.dropna(subset=['Genres'], inplace=True)

**Genre-based Recommender**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
genre = cv.fit_transform(gabung['Genres'])

In [ ]:
gabung[gabung.Genres.isna()]

Empty DataFrame
Columns: [type, Title, Country, date_added, rating, duration, description, Unnamed: 0, ID, Year, Age, IMDb, Rotten Tomatoes, Netflix, Hulu, Prime Video, Disney+, Type, Directors, Genres, Language, Runtime]
Index: []

In [ ]:
cv.get_feature_names()

['action',
 'adventure',
 'animation',
 'biography',
 'comedy',
 'crime',
 'documentary',
 'drama',
 'family',
 'fantasy',
 'filmnoir',
 'gameshow',
 'history',
 'horror',
 'music',
 'musical',
 'mystery',
 'news',
 'realitytv',
 'romance',
 'scifi',
 'short',
 'sport',
 'talkshow',
 'thriller',
 'war',
 'western']

In [ ]:
genre.toarray()

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
df_genre = pd.DataFrame(genre.toarray(), columns=cv.get_feature_names())
df_genre.index = gabung.Title
df_genre.head()

action  adventure  ...  war  western
Title                                                       ...              
Norm of the North: King Sized Adventure       0          1  ...    0        0
#realityhigh                                  0          0  ...    0        0
Automata                                      1          0  ...    0        0
Fabrizio Copano: Solo pienso en mi            0          0  ...    0        0
Good People                                   1          0  ...    0        0

[5 rows x 27 columns]

In [ ]:
from scipy.spatial.distance import pdist, squareform
jaccard_distances = pdist(df_genre.values, metric='jaccard')

In [ ]:
distance_df = pd.DataFrame(1 - squareform(jaccard_distances), index=df_genre.index, columns= df_genre.index)

In [ ]:
distance_df.tail(10)

Title                                Norm of the North: King Sized Adventure  ...  Friends
Title                                                                         ...         
Elaan                                                                  0.000  ...      0.0
Five Nights in Maine                                                   0.000  ...      0.0
Life 2.0                                                               0.000  ...      0.0
Salaakhen                                                              0.000  ...      0.0
The Tenth Man                                                          0.000  ...      0.0
Toro                                                                   0.125  ...      0.0
Frank and Cindy                                                        0.250  ...      0.5
Frank and Cindy                                                        0.250  ...      0.5
Jeremy Scott: The People's Designer                                    0.000  ...      0.0
Friends                                                                0.200  ...      1.0

[10 rows x 2670 columns]

In [ ]:
distance_df = distance_df[~distance_df.index.duplicated()]
test_genre = distance_df[distance_df.index.str.contains('Marvel')].index
genre_df = distance_df.reindex(test_genre)
hasil = pd.DataFrame(genre_df.values.reshape(-1, 1), index=genre_df.columns, columns=['score'])
hasil.sort_values(by='score', ascending=False).head()

score
Title                                                      
LEGO Marvel Super Heroes: Avengers Reassembled!    1.000000
Stretch Armstrong: The Breakout                    1.000000
The Spooky Tale of Captain Underpants Hack-a-ween  0.714286
Kung Fu Panda: Secrets of the Scroll               0.714286
Jimmy Neutron: Boy Genius                          0.714286

**Content-based Recommender**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(min_df = 2, max_df = 0.7, stop_words='english')
desc = tf.fit_transform(netflix['description'])

In [ ]:
tf.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '13',
 '14',
 '14th',
 '15',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1888',
 '1899',
 '18th',
 '19',
 '1900s',
 '1920s',
 '1921',
 '1930s',
 '1940s',
 '1945',
 '1950s',
 '1960s',
 '1961',
 '1962',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1975',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1981',
 '1983',
 '1984',
 '1985',
 '1986',
 '1988',
 '1989',
 '1990s',
 '1991',
 '1992',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '20',
 '200',
 '2001',
 '2003',
 '2006',
 '2008',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '20s',
 '20th',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '30',
 '300',
 '30s',
 '32',
 '33',
 '34',
 '35',
 '36th',
 '3d',
 '40',
 '400',
 '40s',
 '40th',
 '43',
 '45',
 '47',
 '4k',
 '50',
 '500',
 '501',
 '50th',
 '51',
 '60',
 '60s',
 '70s',
 '75',
 '80s',
 '90',
 '90s',
 '99',
 'aamir',
 'aaron',
 'abandoned',
 'abandons',
 'abbey',
 '

In [ ]:
desc.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
desc_df = pd.DataFrame(desc.toarray(), columns=tf.get_feature_names(), index=netflix.Title)
desc_df.head()

000  007   10  ...  zone  zoologist  über
Title                                                   ...                       
Norm of the North: King Sized Adventure  0.0  0.0  0.0  ...   0.0        0.0   0.0
Jandino: Whatever it Takes               0.0  0.0  0.0  ...   0.0        0.0   0.0
Transformers Prime                       0.0  0.0  0.0  ...   0.0        0.0   0.0
Transformers: Robots in Disguise         0.0  0.0  0.0  ...   0.0        0.0   0.0
#realityhigh                             0.0  0.0  0.0  ...   0.0        0.0   0.0

[5 rows x 8235 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# Find similarity between all items
cosine_similarity_array = cosine_similarity(desc_df)
cosine_similarity(desc_df.loc['Friends'].values.reshape(1, -1), 
                  desc_df.loc['#realityhigh'].values.reshape(1, -1))

array([[0.]])

In [ ]:
desc_df = desc_df[~desc_df.index.duplicated()]
test_data = desc_df[desc_df.index.str.contains('Marvel')].index
test_movie = desc_df.reindex(test_data)
test_movie

000  007  ...  zoologist  über
Title                                                        ...                 
Marvel & ESPN Films Present: 1 of 1: Genesis       0.0  0.0  ...        0.0   0.0
LEGO: Marvel Super Heroes: Maximum Overload        0.0  0.0  ...        0.0   0.0
Marvel's Hulk: Where Monsters Dwell                0.0  0.0  ...        0.0   0.0
Marvel Super Hero Adventures: Frost Fight!         0.0  0.0  ...        0.0   0.0
Marvel's Iron Man & Hulk: Heroes United            0.0  0.0  ...        0.0   0.0
LEGO Marvel Super Heroes: Black Panther            0.0  0.0  ...        0.0   0.0
LEGO Marvel Super Heroes: Guardians of the Galaxy  0.0  0.0  ...        0.0   0.0
LEGO Marvel Super Heroes: Avengers Reassembled!    0.0  0.0  ...        0.0   0.0
Marvel's The Defenders                             0.0  0.0  ...        0.0   0.0
Marvel's Iron Fist                                 0.0  0.0  ...        0.0   0.0
Marvel's Agents of S.H.I.E.L.D.                    0.0  0.0  ...        0.0   0.0
Marvel's Daredevil                                 0.0  0.0  ...        0.0   0.0
Marvel's Luke Cage                                 0.0  0.0  ...        0.0   0.0
Marvel's Jessica Jones                             0.0  0.0  ...        0.0   0.0
Marvel's The Punisher                              0.0  0.0  ...        0.0   0.0

[15 rows x 8235 columns]

In [ ]:
test_mean = test_movie.mean()
test_mean.sort_values(ascending=False).head()

avengers    0.092042
marvel      0.064163
iron        0.059632
plot        0.050190
thanos      0.049040
dtype: float64

In [ ]:
unwatched = desc_df.drop(test_data, axis=0)
similar = cosine_similarity(test_mean.values.reshape(1, -1), unwatched)
similar_df = pd.DataFrame(similar.T, index=unwatched.index, columns=["score"])
similar_df.sort_values("score", ascending=False).head(10)

score
Title                                              
Iron Man & Captain America: Heroes United  0.159316
Hulk Vs.                                   0.119618
Pitaah                                     0.116128
Heroes Wanted                              0.111158
Power Rangers Samurai                      0.110686
Power Rangers Ninja Steel                  0.107724
Avengers: Infinity War                     0.107062
Power Rangers Lost Galaxy                  0.104862
Act of Vengeance                           0.100943
Maid-Sama!                                 0.099821